/*
	SDZHotelServicesImplServiceExample.h
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
@interface SDZHotelServicesImplServiceExample : NSObject {
}
-(void)run;
@end
		